import { NextResponse } from "next/server"

import { saveStudioPresetJobAsComposition } from "@/lib/server/composition-jobs-store"

export const runtime = "nodejs"

type RouteContext = {
  params: Promise<{ slug: string; id: string }>
}

// Saves an image generated by a Studio preset into the tenant's Compositions.
export async function POST(_request: Request, context: RouteContext) {
  const { slug, id } = await context.params
  const result = await saveStudioPresetJobAsComposition(slug, id)

  if (!result.ok) {
    return result.reason === "not-ready"
      ? NextResponse.json({ error: "A imagem ainda não está pronta para ser salva." }, { status: 409 })
      : NextResponse.json({ error: "Job de composicao nao encontrado." }, { status: 404 })
  }

  return NextResponse.json({ job: result.job, alreadySaved: result.alreadySaved })
}
